types:
  - Thing

description: >
  A generic container for meta-information.


  ```json

  {
    "@context": {
      "@vocab": "http://schema.org/",
      "µ": "http://micro-api.org/"
    },
    "µ:meta": {
      "@context": null,
      "retrievedAt": "2016-01-09T04:10:09.606Z"
    }
  }

  ```
